logging:
  # standard python logging dict config below here
  # https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
  loggers:
    "laurelin.server":
      level: DEBUG
      handlers: [console]
dit:
  "o=testing":
    data_backend: memory
  "o=test2":
    default: true
    data_backend: memory
servers:
  "ldap://127.0.0.1:10389": {}
