logging:
  # standard python logging dict config below here
  # https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
  loggers:
    "laurelin.server":
      level: DEBUG
      handlers: [console]
schema:
  directory: /some/dir
  allow_undefined_attribute_types: true
dit:
  "o=laurelin":
    data_backend: memory
servers:
  "ldap://0.0.0.0:389": {}
  "ldapi:///var/run/laurelin-server.socket": {}
  "ldaps://0.0.0.0:636":
    certificate: "/etc/laurelin/server/cert_chain.pem"
    private_key: "/etc/laurelin/server/private_key.pem"
    client_verify:
      required: True
      check_crl: True
      use_system_ca_store: True
      ca_file: "/etc/laurelin/server/client_verify_ca.pem"
      ca_path: "/etc/laurelin/server/client_verification_dir"
