# this is a prototype config file for exploring and defining the config language used
# it may or may not represent a working config when taken in its entirety

logging:
  # standard python logging dict config below here
  # https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
  loggers:
    "laurelin.server":
      level: DEBUG
      handlers: [console]
schema:
  directory: /some/dir
  allow_undefined_attribute_types: true
dit:
  "o=laurelin":
    data_backend: memory
auth_backends:
  simple:
    type: simple
    storage: ldap
    name_maps:
      # the first matching search will be used
      - search: '^(.+)$'
        replace: '$1'

    # gets ANDed with (userPassword=*)
    ldap_filter: '(objectClass=user)'

    # one of the laurelin.ldap.DerefAliases constant names
    ldap_deref_aliases: NEVER

    ldap_multiple_passwords: False
  flat_file:
    type: simple
    storage: flat

    flat_filename: /etc/laurelin/server/passwords

    # decides when to read in the flat file
    # valid options:
    #  startup - read in the file once when the server starts up
    #  auth - read in the file for each authentication attempt
    flat_read_mode: startup
auth_stack:
  - backend: simple
    error: break
    user_unknown: continue
    bad_creds: break
  - backend: flat_file
servers:
  "ldap://0.0.0.0:389": {}
  "ldapi:///var/run/laurelin-server.socket": {}
  "ldaps://0.0.0.0:636":
    certificate: "/etc/laurelin/server/cert_chain.pem"
    private_key: "/etc/laurelin/server/private_key.pem"
    client_verify:
      required: True
      check_crl: True
      use_system_ca_store: True
      ca_file: "/etc/laurelin/server/client_verify_ca.pem"
      ca_path: "/etc/laurelin/server/client_verification_dir"
